const Type = {
    STRING:             'STRING',
    INT:                'INT',
    BOOLEAN:            'BOOLEAN',
    CHAR:               'CHAR',
    FUNCTION:           'FUNCTION',
    EXPRESION:          'EXPRESION',
    DOUBLE:             'DOUBLE',
    VOID:               'VOID',
    VALOR:              'VALOR',
    ARRAY:              'ARRAY',
    LIST:               'LIST',
    IF:                 'IF',
    SWITCH:             'SWITCH',
    WHILE:              'WHILE',
    DOWHILE:            'DOWHILE',
    FOR:                'FOR',
    TERNARIO:           'TERNARIO',
    LOGICO:             'LOGICO',
    ARITMETICO:         'ARITMETICO',
    RELACIONAL:         'RELACIONAL',
    MAYOR:              'MAYOR',
    MENOR:              'MENOR',
    IGUAL:              'IGUAL',
    NEGACION:           'NEGACION',
    CASTEO:             'CASTEO',
    NATIVA:             'NATIVA',
    ASINACION:          'ASIGNACION',
    DECLARACION:        'DELARACION',
    PRINT:              'PRINT',
    SUMA:               'SUMA',
    RESTA:              'RESTA',
    MULTIPLICACION:     'MULTIPLIACION',
    DIVISION:           'DIVISION',
    POTENCIA:           'POTENCIA',
    MODULO:             'MODULO',

}
module.exports = Type;